name: Deployment

on:
  push:
    branches: [main]

jobs:
  runs-on: alpine-latest

  steps:
    - uses: actions/checkout@v2
    - uses: actions/node@v2-beta
      with:
        node-version: '14'

    - run: npm i -g yarn
    - name: Installing packages
      run: yarn

    - run: yarn build
    - run: npm install -g surge
    - run: surge ./build URL --token ${{secrets.TOKEN}}
